version: '3'
services:
  ci_flask_docker_test:
    build: .
    ports:
      - "5000:5000"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data_base/test_schema.sql:/docker-entrypoint-initdb.d/init.sql
